git add 3numsort.py*
git add AnimalsVideos.py
git add acode.py*
git add alpha-longest-word.py
git add alphabet-generate-and-reverse.py
git add aployeesdatabase.py
git add areas.py*
git add change.py
git add cls.py*
git add counter.py*
git add dictionary-as-switch.py
git add dinner.py*
git add everyotherlen.py*
git add ex15.py*
git add ex16.py*
git add ex17.py*
git add generators-iterators-basics.py
git add hw-django.py*
git add hw-tkinter.py*
git add indianasalaries.py
git add jsontest.py*
git add loanrepayment.py
git add markgrades.py
git add menu-simple.py
git add printtoyoverxlines.py*
git add quicktry.py*
git add randnum.py*
git add rock-paper-scissors-lizard-spock.py
git add simpleclass.py
git add simpleenc.py*
git add sqltest.py*
git add testargs.py*
git add tktest1.py*
git add word-split.py
git add zen.py*
