pip3 install --upgrade colorama
pip3 install --upgrade decorator
pip3 install --upgrade docutils
pip3 install --upgrade entrypoints
pip3 install --upgrade greenlet
pip3 install --upgrade html5lib
pip3 install --upgrade ipykernel
pip3 install --upgrade ipyparallel
pip3 install --upgrade ipython
pip3 install --upgrade ipywidgets
pip3 install --upgrade jedi
pip3 install --upgrade Jinja2
pip3 install --upgrade jupyter-client
pip3 install --upgrade jupyter-core
pip3 install --upgrade mistune
pip3 install --upgrade nbconvert
pip3 install --upgrade nbformat
pip3 install --upgrade notebook
pip3 install --upgrade numpy
pip3 install --upgrade numpydoc
pip3 install --upgrade openpyxl
pip3 install --upgrade pandocfilters
pip3 install --upgrade pexpect
pip3 install --upgrade prompt-toolkit
pip3 install --upgrade ptyprocess
pip3 install --upgrade python-dateutil
pip3 install --upgrade pytz
pip3 install --upgrade pyzmq
pip3 install --upgrade qtconsole
pip3 install --upgrade regex
pip3 install --upgrade requests
pip3 install --upgrade selenium
pip3 install --upgrade setuptools
pip3 install --upgrade six
pip3 install --upgrade Sphinx
pip3 install --upgrade terminado
pip3 install --upgrade testpath
pip3 install --upgrade tornado
pip3 install --upgrade webencodings
pip3 install --upgrade Werkzeug
pip3 install --upgrade widgetsnbextension
